<?php

namespace App\Http\Controllers\API\TrainingCenter;

use App\Http\Controllers\Controller;
use App\Models\Certificate;
use App\Models\CertificateTemplate;
use App\Models\TrainingClass;
use App\Services\CertificateGenerationService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use OpenApi\Attributes as OA;

class CertificateController extends Controller
{
    protected $certificateGenerationService;

    public function __construct(CertificateGenerationService $certificateGenerationService)
    {
        $this->certificateGenerationService = $certificateGenerationService;
    }
    #[OA\Get(
        path: "/training-center/certificates",
        summary: "List certificates",
        description: "Get all certificates generated by the training center with optional filtering.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        parameters: [
            new OA\Parameter(name: "status", in: "query", schema: new OA\Schema(type: "string", enum: ["valid", "expired", "revoked"]), example: "valid"),
            new OA\Parameter(name: "course_id", in: "query", schema: new OA\Schema(type: "integer"), example: 1),
            new OA\Parameter(name: "per_page", in: "query", schema: new OA\Schema(type: "integer"), example: 15),
            new OA\Parameter(name: "page", in: "query", schema: new OA\Schema(type: "integer"), example: 1)
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: "Certificates retrieved successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "certificates", type: "array", items: new OA\Items(type: "object")),
                        new OA\Property(property: "pagination", type: "object")
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Training center not found")
        ]
    )]
    public function index(Request $request)
    {
        $user = $request->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $query = Certificate::where('training_center_id', $trainingCenter->id)
            ->with(['course', 'instructor', 'template']);

        if ($request->has('course_id')) {
            $query->where('course_id', $request->course_id);
        }

        if ($request->has('status')) {
            $query->where('status', $request->status);
        }

        $perPage = $request->get('per_page', 15);
        $certificates = $query->paginate($perPage);

        return response()->json($certificates);
    }

    #[OA\Get(
        path: "/training-center/certificates/{id}",
        summary: "Get certificate details",
        description: "Get detailed information about a specific certificate.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        parameters: [
            new OA\Parameter(name: "id", in: "path", required: true, schema: new OA\Schema(type: "integer"), example: 1)
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: "Certificate retrieved successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "certificate", type: "object")
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Certificate not found")
        ]
    )]
    public function show($id)
    {
        $certificate = Certificate::with(['course', 'instructor', 'trainingCenter', 'template'])
            ->findOrFail($id);
        return response()->json(['certificate' => $certificate]);
    }

    #[OA\Get(
        path: "/training-center/certificates/templates",
        summary: "Get available certificate templates",
        description: "Get all available certificate templates from authorized ACCs for the training center.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        responses: [
            new OA\Response(
                response: 200,
                description: "Templates retrieved successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "templates", type: "array", items: new OA\Items(type: "object"))
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Training center not found")
        ]
    )]
    public function getTemplates(Request $request)
    {
        $user = $request->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        // Get authorized ACC IDs
        $authorizedAccIds = DB::table('training_center_acc_authorizations')
            ->where('training_center_id', $trainingCenter->id)
            ->where('status', 'approved')
            ->pluck('acc_id');

        // Get active templates from authorized ACCs
        $templates = CertificateTemplate::whereIn('acc_id', $authorizedAccIds)
            ->where('status', 'active')
            ->whereNotNull('background_image_url')
            ->whereNotNull('config_json')
            ->with(['acc', 'category'])
            ->get();

        return response()->json(['templates' => $templates]);
    }

    #[OA\Post(
        path: "/training-center/certificates",
        summary: "Issue a new certificate",
        description: "Generate and issue a new certificate using a template. The system will generate the certificate PDF/image based on the template configuration.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(
                required: ["template_id", "course_id", "trainee_name", "issue_date", "student_data"],
                properties: [
                    new OA\Property(property: "template_id", type: "integer", example: 1),
                    new OA\Property(property: "course_id", type: "integer", example: 1),
                    new OA\Property(property: "class_id", type: "integer", nullable: true, example: 1),
                    new OA\Property(property: "instructor_id", type: "integer", nullable: true, example: 1),
                    new OA\Property(property: "trainee_name", type: "string", example: "John Doe"),
                    new OA\Property(property: "trainee_id_number", type: "string", nullable: true, example: "ID123456"),
                    new OA\Property(property: "issue_date", type: "string", format: "date", example: "2024-01-15"),
                    new OA\Property(property: "expiry_date", type: "string", format: "date", nullable: true, example: "2026-01-15"),
                    new OA\Property(
                        property: "student_data",
                        type: "object",
                        description: "Key-value pairs matching template variables (e.g., {'student_name': 'John Doe', 'course_name': 'Fire Safety'})"
                    )
                ]
            )
        ),
        responses: [
            new OA\Response(response: 201, description: "Certificate issued successfully"),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Template or training center not found"),
            new OA\Response(response: 422, description: "Validation error")
        ]
    )]
    public function store(Request $request)
    {
        $user = $request->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $request->validate([
            'template_id' => 'required|exists:certificate_templates,id',
            'course_id' => 'required|exists:courses,id',
            'class_id' => 'nullable|exists:classes,id',
            'instructor_id' => 'nullable|exists:instructors,id',
            'trainee_name' => 'required|string|max:255',
            'trainee_id_number' => 'nullable|string|max:255',
            'issue_date' => 'required|date',
            'expiry_date' => 'nullable|date|after:issue_date',
            'student_data' => 'required|array',
        ]);

        // Verify template belongs to an authorized ACC
        $template = CertificateTemplate::with('acc')->findOrFail($request->template_id);
        
        $isAuthorized = DB::table('training_center_acc_authorizations')
            ->where('training_center_id', $trainingCenter->id)
            ->where('acc_id', $template->acc_id)
            ->where('status', 'approved')
            ->exists();

        if (!$isAuthorized) {
            return response()->json(['message' => 'Template not available for this training center'], 403);
        }

        // Verify template has required configuration
        if (!$template->background_image_url || !$template->config_json) {
            return response()->json(['message' => 'Template is not properly configured'], 422);
        }

        try {
            // Prepare data for certificate generation
            $certificateData = array_merge($request->student_data, [
                'student_name' => $request->trainee_name,
                'trainee_name' => $request->trainee_name,
                'certificate_number' => $this->generateCertificateNumber(),
                'issue_date' => $request->issue_date,
                'expiry_date' => $request->expiry_date,
            ]);

            // Generate certificate
            $generationResult = $this->certificateGenerationService->generate($template, $certificateData, 'png');

            if (!$generationResult['success']) {
                return response()->json([
                    'message' => 'Failed to generate certificate',
                    'error' => $generationResult['message'] ?? 'Unknown error',
                ], 500);
            }

            // Create certificate record
            $certificate = Certificate::create([
                'certificate_number' => $certificateData['certificate_number'],
                'course_id' => $request->course_id,
                'class_id' => $request->class_id,
                'training_center_id' => $trainingCenter->id,
                'instructor_id' => $request->instructor_id,
                'trainee_name' => $request->trainee_name,
                'trainee_id_number' => $request->trainee_id_number,
                'issue_date' => $request->issue_date,
                'expiry_date' => $request->expiry_date,
                'template_id' => $request->template_id,
                'certificate_pdf_url' => $generationResult['file_url'],
                'verification_code' => $this->generateVerificationCode(),
                'status' => 'valid',
            ]);

            return response()->json([
                'message' => 'Certificate issued successfully',
                'certificate' => $certificate->load(['course', 'instructor', 'template']),
            ], 201);

        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Certificate issuance error', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            return response()->json([
                'message' => 'Failed to issue certificate',
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Generate unique certificate number
     */
    private function generateCertificateNumber(): string
    {
        do {
            $number = 'CERT-' . date('Y') . '-' . strtoupper(Str::random(8));
        } while (Certificate::where('certificate_number', $number)->exists());

        return $number;
    }

    /**
     * Generate unique verification code
     */
    private function generateVerificationCode(): string
    {
        do {
            $code = 'VERIFY-' . strtoupper(Str::random(10));
        } while (Certificate::where('verification_code', $code)->exists());

        return $code;
    }
}
