<?php

namespace App\Http\Controllers\API\TrainingCenter;

use App\Http\Controllers\Controller;
use App\Models\Certificate;
use App\Models\CertificateTemplate;
use App\Models\TrainingClass;
use App\Services\CertificateGenerationService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use OpenApi\Attributes as OA;

class CertificateController extends Controller
{
    protected $certificateGenerationService;

    public function __construct(CertificateGenerationService $certificateGenerationService)
    {
        $this->certificateGenerationService = $certificateGenerationService;
    }
    #[OA\Get(
        path: "/training-center/certificates",
        summary: "List certificates",
        description: "Get all certificates generated by the training center with optional filtering.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        parameters: [
            new OA\Parameter(name: "status", in: "query", schema: new OA\Schema(type: "string", enum: ["valid", "expired", "revoked"]), example: "valid"),
            new OA\Parameter(name: "course_id", in: "query", schema: new OA\Schema(type: "integer"), example: 1),
            new OA\Parameter(name: "per_page", in: "query", schema: new OA\Schema(type: "integer"), example: 15),
            new OA\Parameter(name: "page", in: "query", schema: new OA\Schema(type: "integer"), example: 1)
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: "Certificates retrieved successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "certificates", type: "array", items: new OA\Items(type: "object")),
                        new OA\Property(property: "pagination", type: "object")
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Training center not found")
        ]
    )]
    public function index(Request $request)
    {
        $user = $request->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $query = Certificate::where('training_center_id', $trainingCenter->id)
            ->with(['course', 'instructor', 'template']);

        if ($request->has('course_id')) {
            $query->where('course_id', $request->course_id);
        }

        if ($request->has('status')) {
            $query->where('status', $request->status);
        }

        $perPage = $request->get('per_page', 15);
        $certificates = $query->paginate($perPage);

        return response()->json($certificates);
    }

    #[OA\Get(
        path: "/training-center/certificates/{id}",
        summary: "Get certificate details",
        description: "Get detailed information about a specific certificate.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        parameters: [
            new OA\Parameter(name: "id", in: "path", required: true, schema: new OA\Schema(type: "integer"), example: 1)
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: "Certificate retrieved successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "certificate", type: "object")
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Certificate not found")
        ]
    )]
    public function show($id)
    {
        $user = request()->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $certificate = Certificate::where('training_center_id', $trainingCenter->id)
            ->with(['course', 'instructor', 'trainingCenter', 'template'])
            ->findOrFail($id);
            
        return response()->json(['certificate' => $certificate]);
    }

    #[OA\Get(
        path: "/training-center/certificates/{id}/validity",
        summary: "Check certificate validity",
        description: "Check if a certificate is valid. Returns certificate status and validity information.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        parameters: [
            new OA\Parameter(name: "id", in: "path", required: true, schema: new OA\Schema(type: "integer"), example: 99)
        ],
        responses: [
            new OA\Response(
                response: 200,
                description: "Certificate validity checked successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "valid", type: "boolean", example: true),
                        new OA\Property(property: "status", type: "string", example: "valid"),
                        new OA\Property(property: "certificate", type: "object"),
                        new OA\Property(property: "message", type: "string", example: "Certificate is valid")
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 403, description: "Certificate does not belong to this training center"),
            new OA\Response(response: 404, description: "Certificate not found")
        ]
    )]
    public function checkValidity($id)
    {
        $user = request()->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $certificate = Certificate::where('training_center_id', $trainingCenter->id)
            ->with(['course', 'instructor', 'trainingCenter', 'template'])
            ->findOrFail($id);

        // Check if certificate is expired based on expiry_date
        $isExpired = false;
        if ($certificate->expiry_date && $certificate->expiry_date < now()->toDateString()) {
            $isExpired = true;
            // Update status if not already set
            if ($certificate->status !== 'expired') {
                $certificate->update(['status' => 'expired']);
                $certificate->refresh();
            }
        }

        $isValid = $certificate->status === 'valid' && !$isExpired;
        $status = $certificate->status;

        $message = match($status) {
            'valid' => $isExpired ? 'Certificate has expired' : 'Certificate is valid',
            'expired' => 'Certificate has expired',
            'revoked' => 'Certificate has been revoked',
            default => 'Certificate status: ' . $status,
        };

        return response()->json([
            'valid' => $isValid,
            'status' => $status,
            'message' => $message,
            'certificate' => [
                'id' => $certificate->id,
                'certificate_number' => $certificate->certificate_number,
                'verification_code' => $certificate->verification_code,
                'trainee_name' => $certificate->trainee_name,
                'issue_date' => $certificate->issue_date,
                'expiry_date' => $certificate->expiry_date,
                'status' => $certificate->status,
                'course' => $certificate->course ? [
                    'id' => $certificate->course->id,
                    'name' => $certificate->course->name,
                ] : null,
                'training_center' => $certificate->trainingCenter ? [
                    'id' => $certificate->trainingCenter->id,
                    'name' => $certificate->trainingCenter->name,
                ] : null,
            ],
        ]);
    }

    #[OA\Get(
        path: "/training-center/certificates/{id}/download",
        summary: "Download certificate file",
        description: "Download the certificate PDF/image file.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        parameters: [
            new OA\Parameter(name: "id", in: "path", required: true, schema: new OA\Schema(type: "integer"), example: 99)
        ],
        responses: [
            new OA\Response(response: 200, description: "Certificate file downloaded successfully"),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 403, description: "Certificate does not belong to this training center"),
            new OA\Response(response: 404, description: "Certificate or file not found")
        ]
    )]
    public function download($id)
    {
        $user = request()->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $certificate = Certificate::where('training_center_id', $trainingCenter->id)
            ->findOrFail($id);

        if (!$certificate->certificate_pdf_url) {
            return response()->json(['message' => 'Certificate file not found'], 404);
        }

        try {
            // Extract the file path from the URL
            $url = $certificate->certificate_pdf_url;
            
            if (empty($url)) {
                return response()->json(['message' => 'Certificate file URL is empty'], 404);
            }
            
            // Parse the URL to get the path
            $urlPath = parse_url($url, PHP_URL_PATH);
            if (!$urlPath) {
                $urlPath = $url; // Fallback if parse_url fails
            }
            
            // Remove various URL prefixes to get the storage path
            $filePath = $urlPath;
            
            // Remove /v1/api/storage/ or /api/storage/ prefix if present (handle versioned APIs)
            if (preg_match('#(/v\d+/api/storage/|/api/storage/)(.+)$#', $filePath, $matches)) {
                $filePath = $matches[2];
            }
            // Remove /storage/app/public/ prefix if present
            elseif (strpos($filePath, '/storage/app/public/') !== false) {
                $filePath = str_replace('/storage/app/public/', '', $filePath);
            }
            // Remove /storage/ prefix if present (but not /api/storage/)
            elseif (strpos($filePath, '/storage/') === 0 && strpos($filePath, '/api/storage/') === false) {
                $filePath = substr($filePath, strlen('/storage/'));
            }
            
            // Remove leading slash if present
            $filePath = ltrim($filePath, '/');
            
            // Log for debugging
            \Illuminate\Support\Facades\Log::info('Certificate download attempt', [
                'certificate_id' => $id,
                'original_url' => $url,
                'url_path' => $urlPath,
                'parsed_path' => $filePath,
            ]);
            
            // Check if file exists in storage
            if (!\Illuminate\Support\Facades\Storage::disk('public')->exists($filePath)) {
                // List available files in certificates directory for debugging
                $certDir = dirname($filePath);
                $availableFiles = [];
                if (\Illuminate\Support\Facades\Storage::disk('public')->exists($certDir)) {
                    $availableFiles = \Illuminate\Support\Facades\Storage::disk('public')->files($certDir);
                }
                
                \Illuminate\Support\Facades\Log::warning('Certificate file not found', [
                    'certificate_id' => $id,
                    'url' => $url,
                    'url_path' => $urlPath,
                    'parsed_path' => $filePath,
                    'cert_dir' => $certDir,
                    'available_files' => $availableFiles,
                ]);
                
                return response()->json([
                    'message' => 'Certificate file not found on server',
                    'debug' => config('app.debug') ? [
                        'url' => $url,
                        'url_path' => $urlPath,
                        'parsed_path' => $filePath,
                        'cert_dir' => $certDir,
                    ] : null
                ], 404);
            }

            $fullPath = \Illuminate\Support\Facades\Storage::disk('public')->path($filePath);
            $mimeType = \Illuminate\Support\Facades\Storage::disk('public')->mimeType($filePath) ?? 'application/pdf';
            $fileName = basename($filePath);

            return response()->download($fullPath, $fileName, [
                'Content-Type' => $mimeType,
            ]);

        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json(['message' => 'Certificate not found'], 404);
        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Certificate download error', [
                'certificate_id' => $id,
                'url' => $certificate->certificate_pdf_url ?? 'N/A',
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            return response()->json([
                'message' => 'Failed to download certificate',
                'error' => config('app.debug') ? $e->getMessage() : 'An error occurred',
            ], 500);
        }
    }

    #[OA\Get(
        path: "/training-center/certificates/accs",
        summary: "Get authorized ACCs for certificate generation",
        description: "Get all authorized ACCs that the training center can generate certificates for.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        responses: [
            new OA\Response(
                response: 200,
                description: "ACCs retrieved successfully",
                content: new OA\JsonContent(
                    properties: [
                        new OA\Property(property: "accs", type: "array", items: new OA\Items(type: "object"))
                    ]
                )
            ),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 404, description: "Training center not found")
        ]
    )]
    public function getAuthorizedAccs(Request $request)
    {
        $user = $request->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        // Get authorized ACC IDs
        $authorizedAccIds = DB::table('training_center_acc_authorization')
            ->where('training_center_id', $trainingCenter->id)
            ->where('status', 'approved')
            ->pluck('acc_id');

        // Get ACCs with their info
        $accs = \App\Models\ACC::whereIn('id', $authorizedAccIds)
            ->select('id', 'name', 'logo_url')
            ->get();

        return response()->json(['accs' => $accs]);
    }

    #[OA\Post(
        path: "/training-center/certificates",
        summary: "Issue a new certificate",
        description: "Generate and issue a new certificate. Select ACC and Course, then enter student name. The system will automatically select the appropriate template and generate the certificate.",
        tags: ["Training Center"],
        security: [["sanctum" => []]],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(
                required: ["acc_id", "course_id", "trainee_name", "issue_date"],
                properties: [
                    new OA\Property(property: "acc_id", type: "integer", example: 1, description: "ID of the authorized ACC"),
                    new OA\Property(property: "course_id", type: "integer", example: 1, description: "ID of the course from the selected ACC"),
                    new OA\Property(property: "class_id", type: "integer", nullable: true, example: 1),
                    new OA\Property(property: "instructor_id", type: "integer", nullable: true, example: 1),
                    new OA\Property(property: "trainee_name", type: "string", example: "John Doe", description: "Student name"),
                    new OA\Property(property: "trainee_id_number", type: "string", nullable: true, example: "ID123456"),
                    new OA\Property(property: "issue_date", type: "string", format: "date", example: "2024-01-15"),
                    new OA\Property(property: "expiry_date", type: "string", format: "date", nullable: true, example: "2026-01-15")
                ]
            )
        ),
        responses: [
            new OA\Response(response: 201, description: "Certificate issued successfully"),
            new OA\Response(response: 401, description: "Unauthenticated"),
            new OA\Response(response: 403, description: "ACC not authorized or course not available"),
            new OA\Response(response: 404, description: "ACC, Course, or Template not found"),
            new OA\Response(response: 422, description: "Validation error")
        ]
    )]
    public function store(Request $request)
    {
        $user = $request->user();
        $trainingCenter = \App\Models\TrainingCenter::where('email', $user->email)->first();

        if (!$trainingCenter) {
            return response()->json(['message' => 'Training center not found'], 404);
        }

        $request->validate([
            'acc_id' => 'required|exists:accs,id',
            'course_id' => 'required|exists:courses,id',
            'class_id' => 'nullable|exists:classes,id',
            'instructor_id' => 'nullable|exists:instructors,id',
            'trainee_name' => 'required|string|max:255',
            'trainee_id_number' => 'nullable|string|max:255',
            'issue_date' => 'required|date',
            'expiry_date' => 'nullable|date|after:issue_date',
        ]);

        // Verify ACC is authorized
        $isAuthorized = DB::table('training_center_acc_authorization')
            ->where('training_center_id', $trainingCenter->id)
            ->where('acc_id', $request->acc_id)
            ->where('status', 'approved')
            ->exists();

        if (!$isAuthorized) {
            return response()->json(['message' => 'ACC is not authorized for this training center'], 403);
        }

        // Get course and verify it belongs to the selected ACC
        $course = \App\Models\Course::with(['acc', 'subCategory.category'])->findOrFail($request->course_id);
        
        if ($course->acc_id != $request->acc_id) {
            return response()->json(['message' => 'Course does not belong to the selected ACC'], 403);
        }

        // Find template: must belong to ACC and match course's category
        $categoryId = $course->subCategory->category_id ?? null;
        
        if (!$categoryId) {
            return response()->json(['message' => 'Course category not found'], 422);
        }

        $template = CertificateTemplate::where('acc_id', $request->acc_id)
            ->where('category_id', $categoryId)
            ->where('status', 'active')
            ->whereNotNull('background_image_url')
            ->whereNotNull('config_json')
            ->first();

        if (!$template) {
            return response()->json([
                'message' => 'No certificate template found for this ACC and course category',
                'hint' => 'Please ensure the ACC has created a certificate template for this course category'
            ], 404);
        }

        try {
            // Generate certificate number
            $certificateNumber = $this->generateCertificateNumber();
            
            // Auto-generate student_data from course information
            $certificateData = [
                'student_name' => $request->trainee_name,
                'trainee_name' => $request->trainee_name,
                'course_name' => $course->name,
                'date' => $request->issue_date,
                'cert_id' => $certificateNumber,
                'certificate_number' => $certificateNumber,
                'issue_date' => $request->issue_date,
                'expiry_date' => $request->expiry_date ?? null,
            ];

            // Generate certificate as PDF
            $generationResult = $this->certificateGenerationService->generate($template, $certificateData, 'pdf');

            if (!$generationResult['success']) {
                return response()->json([
                    'message' => 'Failed to generate certificate',
                    'error' => $generationResult['message'] ?? 'Unknown error',
                ], 500);
            }

            // Create certificate record
            $certificate = Certificate::create([
                'certificate_number' => $certificateNumber,
                'course_id' => $request->course_id,
                'class_id' => $request->class_id,
                'training_center_id' => $trainingCenter->id,
                'instructor_id' => $request->instructor_id,
                'trainee_name' => $request->trainee_name,
                'trainee_id_number' => $request->trainee_id_number,
                'issue_date' => $request->issue_date,
                'expiry_date' => $request->expiry_date,
                'template_id' => $template->id,
                'certificate_pdf_url' => $generationResult['file_url'],
                'verification_code' => $this->generateVerificationCode(),
                'status' => 'valid',
            ]);

            return response()->json([
                'message' => 'Certificate issued successfully',
                'certificate' => $certificate->load(['course', 'instructor', 'template']),
            ], 201);

        } catch (\Exception $e) {
            \Illuminate\Support\Facades\Log::error('Certificate issuance error', [
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            return response()->json([
                'message' => 'Failed to issue certificate',
                'error' => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Generate unique certificate number
     */
    private function generateCertificateNumber(): string
    {
        do {
            $number = 'CERT-' . date('Y') . '-' . strtoupper(Str::random(8));
        } while (Certificate::where('certificate_number', $number)->exists());

        return $number;
    }

    /**
     * Generate unique verification code
     */
    private function generateVerificationCode(): string
    {
        do {
            $code = 'VERIFY-' . strtoupper(Str::random(10));
        } while (Certificate::where('verification_code', $code)->exists());

        return $code;
    }
}
